# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2025-10-26 10:06:26
"""
import arcpy
from arcpy.sa import *
from sys import argv

#For inline variable substitution, parameters passed as a String are evaluated using locals(), globals() and isinstance(). To override, substitute values directly.
def PNGtoPolygons(ProjectPNG="6-5(115)_Page_3Test.png", Location="D:\\PRE23\\ryan docs\\Documents\\ArcGIS\\ArcEdit\\OldProjectAdditions", File_GDB_Name):  # PNGtoPolygons

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("3D")
    arcpy.CheckOutExtension("spatial")

    arcpy.ImportToolbox(r"c:\users\cobratype pc\appdata\local\programs\arcgis\pro\Resources\ArcToolbox\toolboxes\Conversion Tools.tbx")
    Reclassification = "0 85 1;85 240 2;241 255 3"
    Expression = "gridcode = 2"

    # Process: Create File Geodatabase (Create File Geodatabase) (management)
    SelectAfunName_gdb = arcpy.management.CreateFileGDB(out_folder_path=Location.__str__().format(**locals(),**globals())if isinstance(Location, str) else Location, out_name="Name")[0]

    # Process: Reclassify (2) (Reclassify) (3d)
    Reclass_655 = fr"{arcpy.env.scratchGDB}\Reclass_655"
    arcpy.ddd.Reclassify(in_raster=ProjectPNG.__str__().format(**locals(),**globals())if isinstance(ProjectPNG, str) else ProjectPNG, reclass_field="Value", remap=Reclassification, out_raster=Reclass_655)
    Reclass_655 = arcpy.Raster(Reclass_655)

    # Process: Raster to Polygon (Raster to Polygon) (conversion)
    OutputPolyName = fr"{arcpy.env.scratchGDB}\RasterT_Reclass5"
    with arcpy.EnvManager(outputMFlag="Disabled", outputZFlag="Disabled"):
        arcpy.conversion.RasterToPolygon(in_raster=Reclass_655, out_polygon_features=OutputPolyName, simplify="NO_SIMPLIFY", raster_field="VALUE")

    # Process: Select (Select) (analysis)
    AreaPreMerg = fr"{arcpy.env.scratchGDB}\AreaPreMerg"
    arcpy.analysis.Select(in_features=OutputPolyName, out_feature_class=AreaPreMerg, where_clause=Expression)

    # Process: Pairwise Dissolve (Pairwise Dissolve) (analysis)
    AreaOutput = fr"{arcpy.env.scratchGDB}\AreaMerged"
    arcpy.analysis.PairwiseDissolve(in_features=AreaPreMerg, out_feature_class=AreaOutput, dissolve_field=["gridcode"], statistics_fields=[["gridcode", "FIRST"]])

    # Process: Select Layer By Attribute (Select Layer By Attribute) (management)
    RasterT_Reclass3_Layer, Count = arcpy.management.SelectLayerByAttribute(in_layer_or_view=OutputPolyName, where_clause="gridcode = 1")

    # Process: Select Layer By Location (Select Layer By Location) (management)
    RasterT_Reclass3_Layer_2_, Output_Layer_Names, Count_2_ = arcpy.management.SelectLayerByLocation(in_layer=[RasterT_Reclass3_Layer], overlap_type="WITHIN_A_DISTANCE", select_features=AreaOutput, search_distance="1 Feet")

    # Process: Select Layer By Attribute (2) (Select Layer By Attribute) (management)
    RasterT_Reclass3_Layer5, Count_3_ = arcpy.management.SelectLayerByAttribute(in_layer_or_view=RasterT_Reclass3_Layer_2_, selection_type="REMOVE_FROM_SELECTION", where_clause="Shape_Area > 40")

    # Process: Calculate Field (Calculate Field) (management)
    RasterT_Reclass3_Layer6 = arcpy.management.CalculateField(in_table=RasterT_Reclass3_Layer5, field="gridcode", expression="2")[0]

    # Process: Merge (2) (Merge) (management)
    FinalMerge = fr"{arcpy.env.scratchGDB}\FinalMerge"
    arcpy.management.Merge(inputs=[AreaOutput, RasterT_Reclass3_Layer6], output=FinalMerge)

    # Process: Polygon to Raster (Polygon to Raster) (conversion)
    FinalMerge_PolygonToRaster = fr"{arcpy.env.scratchGDB}\FinalMerge_PolygonToRaster"
    with arcpy.EnvManager(extent="DEFAULT"):
        arcpy.conversion.PolygonToRaster(in_features=FinalMerge, value_field="gridcode", out_rasterdataset=FinalMerge_PolygonToRaster, cellsize="0.7")

    # Process: Zonal Fill (Zonal Fill) (sa)
    ZonalFi_Fina1 = fr"{arcpy.env.scratchGDB}\ZonalFi_Fina2"
    Zonal_Fill = ZonalFi_Fina1
    ZonalFi_Fina1 = arcpy.sa.ZonalFill(FinalMerge_PolygonToRaster, FinalMerge_PolygonToRaster)
    ZonalFi_Fina1.save(Zonal_Fill)


    # Process: Raster to Polygon (2) (Raster to Polygon) (conversion)
    RasterT_ZonalFi3 = fr"{arcpy.env.scratchGDB}\RasterT_ZonalFi3"
    with arcpy.EnvManager(outputMFlag="Disabled", outputZFlag="Disabled"):
        arcpy.conversion.RasterToPolygon(in_raster=ZonalFi_Fina1, out_polygon_features=RasterT_ZonalFi3, simplify="SIMPLIFY")

    # Process: Pairwise Dissolve (2) (Pairwise Dissolve) (analysis)
    RasterToPolyFinal = fr"{arcpy.env.scratchGDB}\RasterToPolyFinal"
    arcpy.analysis.PairwiseDissolve(in_features=RasterT_ZonalFi3, out_feature_class=RasterToPolyFinal, dissolve_field=["gridcode"])

    # Process: Feature Class To Geodatabase (Feature Class To Geodatabase) (conversion)
    _gdb = arcpy.conversion.FeatureClassToGeodatabase(Input_Features=[RasterToPolyFinal], Output_Geodatabase=Location.__str__().format(**locals(),**globals())if isinstance(Location, str) else Location)[0]

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\Users\\Cobratype PC\\Documents\\ArcGIS\\Projects\\Admin\\Admin.gdb", workspace="C:\\Users\\Cobratype PC\\Documents\\ArcGIS\\Projects\\Admin\\Admin.gdb"):
        PNGtoPolygons(*argv[1:])
