var BarData = 
   {
   "type": "FeatureCollection",
   "features": [
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ -96.7068432,40.81462 ]
    },
    "properties": {
    "#NAME?":"way/203844164",
    "amenity":"bar",
    "building":"yes",
    "name":"Single Barrel",
    "source":"bing",
    "addr:housenumber":"",
    "addr:street":"",
    "cuisine":"",
    "disused:amenity":"",
    "addr:city":"",
    "addr:state":"",
    "is_in:city":"",
    "is_in:state":"",
    "is_in:state_code":"",
    "addr:country":"",
    "addr:postcode":null,
    "disused:cuisine":"",
    "internet_access":"",
    "internet_access:fee":"",
    "opening_hours":"11:00 - 22:00",
    "phone":"402-904-4631",
    "smoking":"",
    "smoking:outside":"",
    "wheelchair":"",
    "wikidata":"",
    "takeaway":"",
    "website":"<a herf=\"https://www.thesinglebarrel.com\">TheSingleBarrel.com</a>",
    "alt_name":"",
    "email":"",
    "addr:housename":"",
    "description:en":"",
    "operator":"",
    "outdoor_seating":"",
    "atm":"",
    "note":""
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ -96.7015996,40.8149502 ]
    },
    "properties": {
    "#NAME?":"node/1922497332",
    "amenity":"pub",
    "building":"",
    "name":"Stogies Bar",
    "source":"",
    "addr:housenumber":"1332",
    "addr:street":"P Street",
    "cuisine":"pizza",
    "disused:amenity":"restaurant",
    "addr:city":"",
    "addr:state":"",
    "is_in:city":"",
    "is_in:state":"",
    "is_in:state_code":"",
    "addr:country":"",
    "addr:postcode":null,
    "disused:cuisine":"",
    "internet_access":"",
    "internet_access:fee":"",
    "opening_hours":"12:00 - 02:00",
    "phone":"None available",
    "smoking":"",
    "smoking:outside":"",
    "wheelchair":"",
    "wikidata":"",
    "takeaway":"",
    "website":"<a herf=\"https://www.facebook.com/1332Pstreet/\">Stogies Facebook Page</a>",
    "alt_name":"",
    "email":"",
    "addr:housename":"",
    "description:en":"",
    "operator":"",
    "outdoor_seating":"",
    "atm":"",
    "note":""
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ -96.7052988,40.8140955 ]
    },
    "properties": {
    "#NAME?":"node/1923741851",
    "amenity":"bar",
    "building":"",
    "name":"The Happy Raven",
    "source":"",
    "addr:housenumber":"",
    "addr:street":"",
    "cuisine":"",
    "disused:amenity":"",
    "addr:city":"Lincoln",
    "addr:state":"NE",
    "is_in:city":"Lincoln",
    "is_in:state":"Nebraska",
    "is_in:state_code":"NE",
    "addr:country":"",
    "addr:postcode":null,
    "disused:cuisine":"",
    "internet_access":"",
    "internet_access:fee":"",
    "opening_hours":"13:00 - 20:00",
    "phone":"402-472-0004",
    "smoking":"",
    "smoking:outside":"",
    "wheelchair":"",
    "wikidata":"",
    "takeaway":"",
    "website":"<a herf=\"https://www.thehappyraven.com/\">TheHappyRaven.com</a>",
    "alt_name":"",
    "email":"",
    "addr:housename":"",
    "description:en":"",
    "operator":"",
    "outdoor_seating":"",
    "atm":"",
    "note":""
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ -96.7009492,40.814383 ]
    },
    "properties": {
    "#NAME?":"node/1923925358",
    "amenity":"pub",
    "building":"",
    "name":"Zoo Bar",
    "source":"",
    "addr:housenumber":"",
    "addr:street":"",
    "cuisine":"",
    "disused:amenity":"",
    "addr:city":"",
    "addr:state":"",
    "is_in:city":"",
    "is_in:state":"",
    "is_in:state_code":"",
    "addr:country":"",
    "addr:postcode":null,
    "disused:cuisine":"",
    "internet_access":"",
    "internet_access:fee":"",
    "opening_hours":"15:00 - 02:00",
    "phone":"402-435-8754",
    "smoking":"",
    "smoking:outside":"",
    "wheelchair":"",
    "wikidata":"Q8074037",
    "takeaway":"",
    "website":"<a herf=\"http://www.zoobar.com/\">ZooBar.com</a>",
    "alt_name":"",
    "email":"",
    "addr:housename":"",
    "description:en":"",
    "operator":"",
    "outdoor_seating":"",
    "atm":"",
    "note":""
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ -96.7004505,40.8134367 ]
    },
    "properties": {
    "#NAME?":"node/1924473791",
    "amenity":"bar",
    "building":"",
    "name":"Yia Yia's",
    "source":"",
    "addr:housenumber":"1423",
    "addr:street":"O Street",
    "cuisine":"pizza",
    "disused:amenity":"",
    "addr:city":"Lincoln",
    "addr:state":"NE",
    "is_in:city":"",
    "is_in:state":"",
    "is_in:state_code":"",
    "addr:country":"US",
    "addr:postcode":68508,
    "disused:cuisine":"",
    "internet_access":"",
    "internet_access:fee":"",
    "opening_hours":"11:00 - 21:00",
    "phone":"402-477-9166",
    "smoking":"no",
    "smoking:outside":"yes",
    "wheelchair":"yes",
    "wikidata":"",
    "takeaway":"yes",
    "website":"<a herf=\"https://www.yiayiaspizzaandbeer.com/\">YiaYias Website</a>",
    "alt_name":"",
    "email":"",
    "addr:housename":"",
    "description:en":"",
    "operator":"",
    "outdoor_seating":"",
    "atm":"",
    "note":""
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ -96.7007266,40.8137742 ]
    },
    "properties": {
    "#NAME?":"node/1946858992",
    "amenity":"bar",
    "building":"",
    "name":"Duffy's Tavern",
    "source":"",
    "addr:housenumber":"",
    "addr:street":"",
    "cuisine":"",
    "disused:amenity":"",
    "addr:city":"",
    "addr:state":"",
    "is_in:city":"",
    "is_in:state":"",
    "is_in:state_code":"",
    "addr:country":"",
    "addr:postcode":null,
    "disused:cuisine":"",
    "internet_access":"",
    "internet_access:fee":"",
    "opening_hours":"16:00 - 02:00",
    "phone":"402-477-3543",
    "smoking":"",
    "smoking:outside":"yes",
    "wheelchair":"",
    "wikidata":"",
    "takeaway":"",
    "website":"<a herf=\"http://www.duffyslincoln.com/\">DuffysLincoln.com</a>",
    "alt_name":"",
    "email":"",
    "addr:housename":"",
    "description:en":"",
    "operator":"",
    "outdoor_seating":"",
    "atm":"",
    "note":""
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ -96.7102505,40.8160359 ]
    },
    "properties": {
    "#NAME?":"node/2189324402",
    "amenity":"pub",
    "building":"",
    "name":"LeadBelly",
    "source":"",
    "addr:housenumber":"301",
    "addr:street":"North 8th Street",
    "cuisine":"american",
    "disused:amenity":"",
    "addr:city":"Lincoln",
    "addr:state":"",
    "is_in:city":"",
    "is_in:state":"",
    "is_in:state_code":"",
    "addr:country":"",
    "addr:postcode":68508,
    "disused:cuisine":"",
    "internet_access":"",
    "internet_access:fee":"",
    "opening_hours":"11:00 - 24:00",
    "phone":"402-261-8849",
    "smoking":"",
    "smoking:outside":"",
    "wheelchair":"",
    "wikidata":"",
    "takeaway":"",
    "website":"<a herf=\"https://www.getleaded.com/\">Leadbelly Website</a>",
    "alt_name":"LeadBelly Contemporary American Pub",
    "email":"info@getleaded.com",
    "addr:housename":"",
    "description:en":"",
    "operator":"",
    "outdoor_seating":"",
    "atm":"",
    "note":""
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ -96.7008746,40.8134155 ]
    },
    "properties": {
    "#NAME?":"node/2315669873",
    "amenity":"bar",
    "building":"",
    "name":"Sandy's",
    "source":"",
    "addr:housenumber":"",
    "addr:street":"",
    "cuisine":"",
    "disused:amenity":"",
    "addr:city":"",
    "addr:state":"",
    "is_in:city":"",
    "is_in:state":"",
    "is_in:state_code":"",
    "addr:country":"",
    "addr:postcode":null,
    "disused:cuisine":"",
    "internet_access":"",
    "internet_access:fee":"",
    "opening_hours":"18:00 - 02:00",
    "phone":"402-475-2418",
    "smoking":"",
    "smoking:outside":"",
    "wheelchair":"",
    "wikidata":"",
    "takeaway":"",
    "website":"<a herf=\"https://www.facebook.com/SandysLincoln/\">Sandys Lincoln Facebook Page</a>",
    "alt_name":"",
    "email":"",
    "addr:housename":"",
    "description:en":"",
    "operator":"",
    "outdoor_seating":"",
    "atm":"",
    "note":""
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ -96.7007699,40.813377 ]
    },
    "properties": {
    "#NAME?":"node/2315669987",
    "amenity":"bar",
    "building":"",
    "name":"Fat Toad",
    "source":"",
    "addr:housenumber":"",
    "addr:street":"",
    "cuisine":"",
    "disused:amenity":"",
    "addr:city":"",
    "addr:state":"",
    "is_in:city":"",
    "is_in:state":"",
    "is_in:state_code":"",
    "addr:country":"",
    "addr:postcode":null,
    "disused:cuisine":"",
    "internet_access":"",
    "internet_access:fee":"",
    "opening_hours":"21:00 - 02:00",
    "phone":"402-438-3311",
    "smoking":"",
    "smoking:outside":"",
    "wheelchair":"",
    "wikidata":"",
    "takeaway":"",
    "website":"<a herf=\"https://www.facebook.com/FatToadPub/\">The Fat Toad Pub Facebook Page</a>",
    "alt_name":"",
    "email":"",
    "addr:housename":"",
    "description:en":"",
    "operator":"",
    "outdoor_seating":"",
    "atm":"",
    "note":""
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ -96.7013816,40.8145564 ]
    },
    "properties": {
    "#NAME?":"node/2315681501",
    "amenity":"pub",
    "building":"",
    "name":"Jake's Cigars",
    "source":"",
    "addr:housenumber":"",
    "addr:street":"",
    "cuisine":"",
    "disused:amenity":"",
    "addr:city":"",
    "addr:state":"",
    "is_in:city":"",
    "is_in:state":"",
    "is_in:state_code":"",
    "addr:country":"",
    "addr:postcode":null,
    "disused:cuisine":"",
    "internet_access":"",
    "internet_access:fee":"",
    "opening_hours":"11:00 - 22:00",
    "phone":"402-261-5944",
    "smoking":"",
    "smoking:outside":"",
    "wheelchair":"",
    "wikidata":"",
    "takeaway":"",
    "website":"<a herf=\"https://jakescigars.com/\">Jakes Cigar Lounge</a>",
    "alt_name":"",
    "email":"",
    "addr:housename":"",
    "description:en":"",
    "operator":"",
    "outdoor_seating":"",
    "atm":"",
    "note":""
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ -96.7108086,40.8146061 ]
    },
    "properties": {
    "#NAME?":"node/2869723464",
    "amenity":"bar",
    "building":"",
    "name":"McKinney's Irish Pub",
    "source":"",
    "addr:housenumber":"151-#140",
    "addr:street":"North 8th Street",
    "cuisine":"",
    "disused:amenity":"",
    "addr:city":"Lincoln",
    "addr:state":"",
    "is_in:city":"",
    "is_in:state":"",
    "is_in:state_code":"",
    "addr:country":"",
    "addr:postcode":68508,
    "disused:cuisine":"",
    "internet_access":"",
    "internet_access:fee":"",
    "opening_hours":"11:00 - 02:00",
    "phone":"402-477-0021",
    "smoking":"",
    "smoking:outside":"",
    "wheelchair":"",
    "wikidata":"",
    "takeaway":"",
    "website":"<a herf=\"http://mckinneyspublincoln.com/\">McKinney's Irish Pub Website</a>",
    "alt_name":"",
    "email":"",
    "addr:housename":"",
    "description:en":"",
    "operator":"",
    "outdoor_seating":"",
    "atm":"",
    "note":""
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ -96.7097236,40.8138762 ]
    },
    "properties": {
    "#NAME?":"node/3146595663",
    "amenity":"bar",
    "building":"",
    "name":"Jack's Bar and Grill",
    "source":"",
    "addr:housenumber":"100",
    "addr:street":"North 8th Street",
    "cuisine":"",
    "disused:amenity":"",
    "addr:city":"Lincoln",
    "addr:state":"",
    "is_in:city":"",
    "is_in:state":"",
    "is_in:state_code":"",
    "addr:country":"",
    "addr:postcode":68508,
    "disused:cuisine":"",
    "internet_access":"",
    "internet_access:fee":"",
    "opening_hours":"12:00 - 02:00",
    "phone":"402-438-6288",
    "smoking":"",
    "smoking:outside":"",
    "wheelchair":"",
    "wikidata":"",
    "takeaway":"",
    "website":"<a herf=\"https://www.facebook.com/jacksbarlincoln\">Jacks Bar Facebook Page</a>",
    "alt_name":"",
    "email":"",
    "addr:housename":"Armour Building",
    "description:en":"",
    "operator":"",
    "outdoor_seating":"",
    "atm":"",
    "note":""
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ -96.7105429,40.8155873 ]
    },
    "properties": {
    "#NAME?":"node/3148230783",
    "amenity":"pub",
    "building":"",
    "name":"Empyrean Brewing Co.",
    "source":"",
    "addr:housenumber":"729",
    "addr:street":"Q Street",
    "cuisine":"",
    "disused:amenity":"",
    "addr:city":"Lincoln",
    "addr:state":"",
    "is_in:city":"",
    "is_in:state":"",
    "is_in:state_code":"",
    "addr:country":"",
    "addr:postcode":68508,
    "disused:cuisine":"",
    "internet_access":"",
    "internet_access:fee":"",
    "opening_hours":"08:00 - 17:00",
    "phone":"402-434-5960",
    "smoking":"",
    "smoking:outside":"",
    "wheelchair":"",
    "wikidata":"",
    "takeaway":"",
    "website":"<a herf=\"https://empyreanbrewingco.com/\">Empryrian Brewing Company Website</a>",
    "alt_name":"Empyrean Ales",
    "email":"",
    "addr:housename":"",
    "description:en":"",
    "operator":"",
    "outdoor_seating":"",
    "atm":"",
    "note":""
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ -96.7090969,40.8152789 ]
    },
    "properties": {
    "#NAME?":"node/4035893511",
    "amenity":"bar",
    "building":"",
    "name":"The Other Room",
    "source":"",
    "addr:housenumber":"",
    "addr:street":"",
    "cuisine":"",
    "disused:amenity":"",
    "addr:city":"",
    "addr:state":"",
    "is_in:city":"",
    "is_in:state":"",
    "is_in:state_code":"",
    "addr:country":"",
    "addr:postcode":null,
    "disused:cuisine":"",
    "internet_access":"",
    "internet_access:fee":"",
    "opening_hours":"17:00 - 02:00",
    "phone":"402-261-4608",
    "smoking":"no",
    "smoking:outside":"",
    "wheelchair":"",
    "wikidata":"",
    "takeaway":"",
    "website":"<a herf=\"https://www.facebook.com/theotherroomlincoln/\">The Other Room Facebook Page</a>",
    "alt_name":"",
    "email":"",
    "addr:housename":"",
    "description:en":"Pre-prohibition era bar, no cell phone use allowed. Minimum capacity occupancy.",
    "operator":"Jill",
    "outdoor_seating":"",
    "atm":"",
    "note":""
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ -96.7121085,40.8144062 ]
    },
    "properties": {
    "#NAME?":"node/4472146825",
    "amenity":"pub",
    "building":"",
    "name":"HopCat",
    "source":"",
    "addr:housenumber":"",
    "addr:street":"",
    "cuisine":"",
    "disused:amenity":"",
    "addr:city":"",
    "addr:state":"",
    "is_in:city":"",
    "is_in:state":"",
    "is_in:state_code":"",
    "addr:country":"",
    "addr:postcode":null,
    "disused:cuisine":"",
    "internet_access":"",
    "internet_access:fee":"",
    "opening_hours":"11:00 - 22:00",
    "phone":"402-971-0700",
    "smoking":"",
    "smoking:outside":"",
    "wheelchair":"",
    "wikidata":"",
    "takeaway":"",
    "website":"<a herf=\"https://hopcat.com/lincoln\">Hopcat Lincoln Website</a>",
    "alt_name":"",
    "email":"",
    "addr:housename":"",
    "description:en":"",
    "operator":"",
    "outdoor_seating":"yes",
    "atm":"",
    "note":""
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ -96.700389,40.8138042 ]
    },
    "properties": {
    "#NAME?":"node/6516537069",
    "amenity":"pub",
    "building":"",
    "name":"Iguana's Pub",
    "source":"",
    "addr:housenumber":"",
    "addr:street":"O St.",
    "cuisine":"",
    "disused:amenity":"",
    "addr:city":"",
    "addr:state":"",
    "is_in:city":"",
    "is_in:state":"",
    "is_in:state_code":"",
    "addr:country":"",
    "addr:postcode":null,
    "disused:cuisine":"",
    "internet_access":"",
    "internet_access:fee":"",
    "opening_hours":"20:00 - 02:00",
    "phone":"402-476-8850",
    "smoking":"",
    "smoking:outside":"",
    "wheelchair":"",
    "wikidata":"",
    "takeaway":"",
    "website":"<a herf=\"https://www.facebook.com/iguanaslincoln/\">Iguanas Facebook</a>",
    "alt_name":"",
    "email":"",
    "addr:housename":"",
    "description:en":"",
    "operator":"",
    "outdoor_seating":"",
    "atm":"",
    "note":""
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ -96.7038333,40.8138274 ]
    },
    "properties": {
    "#NAME?":"node/6993160057",
    "amenity":"pub",
    "building":"",
    "name":"12th Street Pub",
    "source":"",
    "addr:housenumber":"1200",
    "addr:street":"O Street",
    "cuisine":"",
    "disused:amenity":"",
    "addr:city":"Lincoln",
    "addr:state":"NE",
    "is_in:city":"",
    "is_in:state":"",
    "is_in:state_code":"",
    "addr:country":"",
    "addr:postcode":68508,
    "disused:cuisine":"",
    "internet_access":"",
    "internet_access:fee":"",
    "opening_hours":"19:00 - 01:00",
    "phone":"402-435-3358",
    "smoking":"",
    "smoking:outside":"",
    "wheelchair":"",
    "wikidata":"",
    "takeaway":"",
    "website":"<a herf=\"https://www.facebook.com/12thStreetPub/\">12th Street Pub Facebook</a>",
    "alt_name":"",
    "email":"",
    "addr:housename":"",
    "description:en":"",
    "operator":"",
    "outdoor_seating":"",
    "atm":"yes",
    "note":""
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ -96.7038666,40.8144622 ]
    },
    "properties": {
    "#NAME?":"node/6993160059",
    "amenity":"bar",
    "building":"",
    "name":"Captain Jack's Bar",
    "source":"",
    "addr:housenumber":"140",
    "addr:street":"North 12th Street",
    "cuisine":"",
    "disused:amenity":"",
    "addr:city":"Lincoln",
    "addr:state":"NE",
    "is_in:city":"",
    "is_in:state":"",
    "is_in:state_code":"",
    "addr:country":"",
    "addr:postcode":68508,
    "disused:cuisine":"",
    "internet_access":"",
    "internet_access:fee":"",
    "opening_hours":"12:00 - 02:00",
    "phone":"402-770-7659",
    "smoking":"",
    "smoking:outside":"",
    "wheelchair":"",
    "wikidata":"",
    "takeaway":"",
    "website":"<a herf=\"https://www.facebook.com/CaptainJacksBar/\">Captain Jacks Facebook</a>",
    "alt_name":"",
    "email":"",
    "addr:housename":"",
    "description:en":"",
    "operator":"",
    "outdoor_seating":"no",
    "atm":"",
    "note":""
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ -96.7052523,40.8152488 ]
    },
    "properties": {
    "#NAME?":"node/7217846193",
    "amenity":"bar",
    "building":"",
    "name":"Boitano's Lounge",
    "source":"",
    "addr:housenumber":"216",
    "addr:street":"North 11th Street",
    "cuisine":"",
    "disused:amenity":"",
    "addr:city":"Lincoln",
    "addr:state":"NE",
    "is_in:city":"",
    "is_in:state":"",
    "is_in:state_code":"",
    "addr:country":"",
    "addr:postcode":68508,
    "disused:cuisine":"",
    "internet_access":"",
    "internet_access:fee":"",
    "opening_hours":"16:00 - 24:00",
    "phone":"(402) 261-7800",
    "smoking":"",
    "smoking:outside":"",
    "wheelchair":"",
    "wikidata":"",
    "takeaway":"",
    "website":"<a href=\"https://thekindlerhotel.com/amenities/\">Boitanos Lounge</a>",
    "alt_name":"",
    "email":"",
    "addr:housename":"The Kindler Hotel",
    "description:en":"",
    "operator":"Brian Boitano;The Kindler Hotel",
    "outdoor_seating":"",
    "atm":"",
    "note":"located within The Kindler Hotel"
    }
  }
]
};